In [5]:
from nba_api.stats.endpoints import playercareerstats, commonteamyears
from nba_api.stats.static import teams, players
nba_team = teams.get_teams()
player = players.get_inactive_players()
# print(player)
gary_payton = [p for p in player if player['last_name'] == "Durant"][0]
# # print(gary_payton)

gp_id = gary_payton["id"]
# # Anthony Davis
career = playercareerstats.PlayerCareerStats(player_id=gp_id)
career.get_data_frames()[0]

# cty = commonteamyears.CommonTeamYears().get_data_frames()[0]

# print(cty)

TypeError: list indices must be integers or slices, not str

In [22]:
from nba_api.stats.static import teams, players
nba_team = teams.get_teams()
celtics = [team for team in nba_team if team["abbreviation"] == "BOS"][0]
celtics_id = celtics['id']

from nba_api.stats.endpoints import leaguegamefinder, teamdetails

gamefinder = leaguegamefinder.LeagueGameFinder(team_id_nullable=celtics_id)
details = teamdetails.TeamDetails(team_id=celtics_id)
# games = gamefinder.get_data_frames()[0]
# games
d = details.get_data_frames()[0]
d

,TEAM_ID,ABBREVIATION,NICKNAME,YEARFOUNDED,CITY,ARENA,ARENACAPACITY,OWNER,GENERALMANAGER,HEADCOACH,DLEAGUEAFFILIATION
0,1610612738,BOS,Celtics,1946,Boston,TD Garden,18624,Wyc Grousbeck,Brad Stevens,Ime Udoka,Maine Celtics

In [5]:
celtics = [team for team in nba_team if team['abbreviation'] == "GSW"][0]
celtics_id = celtics['id']

from nba_api.stats.endpoints import leaguegamefinder, teamdetails

gamefinder = leaguegamefinder.LeagueGameFinder(team_id_nullable=celtics_id)
details = teamdetails.TeamDetails(team_id=celtics_id)
games = gamefinder.get_data_frames()[0]
games

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
0,22022,1610612744,GSW,Golden State Warriors,1522200074,2022-07-17,GSW vs. WAS,L,201,77,...,0.667,12.0,33.0,45.0,15,6,6,21,20,-10.0
1,22022,1610612744,GSW,Golden State Warriors,1522200056,2022-07-15,GSW vs. OKC,L,202,82,...,0.667,4.0,31.0,35.0,14,7,3,16,23,-8.0
2,22022,1610612744,GSW,Golden State Warriors,1522200035,2022-07-12,GSW vs. BOS,L,199,92,...,0.667,16.0,22.0,38.0,14,7,8,13,23,-18.4
3,22022,1610612744,GSW,Golden State Warriors,1522200023,2022-07-10,GSW @ SAS,W,200,86,...,0.581,13.0,25.0,38.0,14,7,6,16,30,1.0
4,22022,1610612744,GSW,Golden State Warriors,1522200007,2022-07-08,GSW @ NYK,L,200,88,...,0.700,11.0,28.0,39.0,13,8,4,23,20,-10.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3504,21983,1610612744,GOS,Golden State Warriors,0028300048,1983-11-05,GOS vs. NYK,W,240,102,...,0.711,25.0,18.0,43.0,20,16,4,17,27,NaN
3505,21983,1610612744,GOS,Golden State Warriors,0028300040,1983-11-03,GOS @ UTH,L,240,112,...,0.880,27.0,26.0,53.0,22,11,4,19,31,NaN
3506,21983,1610612744,GOS,Golden State Warriors,0028300029,1983-11-01,GOS @ KCK,L,240,114,...,0.750,12.0,18.0,30.0,29,15,3,16,28,NaN
3507,21983,1610612744,GOS,Golden State Warriors,0028300013,1983-10-29,GOS vs. POR,W,240,97,...,0.725,12.0,31.0,43.0,21,9,1,16,37,NaN
3508,21983,1610612744,GOS,Golden State Warriors,0028300004,1983-10-28,GOS @ SEA,W,240,110,...,0.703,21.0,26.0,47.0,26,11,2,19,34,NaN

In [18]:
from nba_api.stats.endpoints import playercareerstats
# Anthony Davis
career = playercareerstats.PlayerCareerStats(player_id='203090')
career.get_data_frames()[0]

,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,FGM,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,203090,2012-13,00,1610612753,ORL,20.0,76,59,1974.0,260,...,0.570,122,213,335,50,88,62,69,144,625
1,203090,2013-14,00,1610612753,ORL,21.0,80,41,1950.0,224,...,0.594,69,195,264,80,97,50,86,140,592
2,203090,2014-15,00,1610612753,ORL,22.0,45,4,674.0,63,...,0.537,38,68,106,25,32,9,27,66,158
3,203090,2015-16,00,1610612757,POR,23.0,78,14,1457.0,195,...,0.622,101,179,280,67,49,35,62,124,498
4,203090,2016-17,00,1610612757,POR,24.0,77,69,2223.0,314,...,0.621,125,216,341,88,85,70,86,214,773
5,203090,2017-18,00,1610612757,POR,25.0,59,37,1264.0,147,...,0.712,46,116,162,53,48,43,40,103,385
6,203090,2018-19,00,1610612757,POR,26.0,60,53,1415.0,189,...,0.671,77,192,269,74,67,53,45,163,460
7,203090,2019-20,00,1610612746,LAC,27.0,50,38,1141.0,112,...,0.571,47,153,200,48,49,30,46,120,275
8,203090,2019-20,00,1610612752,NYK,27.0,12,10,286.0,30,...,0.625,8,32,40,20,9,3,7,28,82
9,203090,2019-20,00,0,TOT,27.0,62,48,1427.0,142,...,0.591,55,185,240,68,58,33,53,148,357
10,203090,2020-21,00,1610612748,MIA,28.0,11,3,124.0,5,...,0.000,2,11,13,7,2,4,3,14,15
11,203090,2020-21,00,1610612758,SAC,28.0,26,20,648.0,64,...,0.805,11,65,76,37,28,16,19,72,179
12,203090,2020-21,00,0,TOT,28.0,37,23,772.0,69,...,0.767,13,76,89,44,30,20,22,86,194
13,203090,2021-22,00,1610612758,SAC,29.0,47,24,864.0,83,...,0.714,12,100,112,23,29,24,31,77,217